---
- name: install tcpdump
  yum:
    name: 
      - tcpdump
    state: present

- name: install dhcp
  yum:
    name: 
      - dhcp
    state: present

- name: install tftp server
  yum:
    name: 
      - tftp
      - tftp-server
      - xinetd
    state: present

- name: enable service and start dhcp, xinetd, and tftp
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
      - "dhcpd"
      - "xinetd"
      - "tftp"

- name: Install dhcp config file
  template:
    src: dhcpd.conf.j2
    dest: "{{ dhcp_config }}"
    owner: root
    group: root
    mode: 0644
    validate: 'dhcpd -t -cf %s'
  notify: restart dhcpd