---
- name: install dhcp
  yum:
    name: 
      - dhcp
    state: present

- name: install tftp server
  yum:
    name: 
      - tftp
      - tftp-server
      - xinetd
    state: present

- name: enable service and start dhcp, xinetd, and tftp
  systemd:
    name: "{{ service }}"
    enabled: yes
  loop:
      - "dhcpd"
      - "xinetd"
      - "tftp"
  loop_control:
    loop_var: service

- name: Install tftp config file
  template: 
    src: "{{ tftp_template }}"
    dest: "{{ tftp_config_path }}{{ tftp_config }}"
    owner: root
    group: root
    mode: 0644
  notify: 
    - restart tftp

- name: Install dhcp config file
  template:
    src: "{{ dhcp_template }}"
    dest: "{{ dhcp_config_path }}{{ dhcp_config }}"
    owner: root
    group: root
    mode: 0644
    validate: 'dhcpd -t -cf %s'
  notify: 
    - restart dhcpd