---
dhcp_config_path: /etc/dhcp/
dhcp_config: dhcpd.conf
dhcp_template: dhcpd.conf.j2
dhcp_server: 192.168.2.1
dhcp_subnet: 192.168.2.0
dhcp_netmask: 255.255.255.0
poap_script: nxos_poap.py
dhcp_range: 
  low: 192.168.2.2
  high: 192.168.2.2

## TFTP vars

tftp_config_path: /etc/xinetd.d/
tftp_config: tftp
tftp_template: tftp.j2
