---
- name: Generate spine configs
  template:
    src: spine.j2
    dest: "{{ tftp_dir }}/{{ cfg_name }}"
    owner: root
    group: root
    mode: 0644

- name: Get md5sum
  stat: 
    path: "{{ tftp_dir }}/{{ cfg_name }}"
    get_checksum: true
    checksum_algorithm: md5
  register: st

- debug:
    msg: "{{ st.stat.checksum }}"

- name: Create Config MD5 File
  copy: 
    dest: "{{ tftp_dir }}/{{ cfg_name }}.md5"
    content: "{{ st.stat.checksum }} {{ st.stat.path }}"
    owner: root
    group: root
    mode: 0644

